name: adbrixrm_flutter
description: AdBrix Remastered plugin for Flutter project. AdBrix is a global Attribution and Analytics tool for Android and iOS app.
version: 1.6.0
homepage: https://www.dfinery.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.igaworks.adbrixrm_flutter
        pluginClass: AdbrixrmFlutterPlugin
      ios:
        pluginClass: AdbrixrmFlutterPlugin
